### ISSUE TITLE
Some message ids are ignored

### ISSUE THREAD

**Issue by mydea** [Cropster/ember-l10n#2] opened 2016-06-29 09:55 UTC
The following string: `{{t '<No Name'}}` leads to an empty string. `{{t '< No Name >'}}` works, though. Note that for this case, the string was not in the en.json file yet.

**Comment by arm1n** [comment] 2016-07-04 05:46
I guess that this is caused by the regex of the [xgettext parser](https://github.com/gmarty/xgettext) interpreting `<` and `>` as HTML tags. At the moment I don't know how to implement a meaningful fix for this issue.

**Comment by arm1n** [comment] 2017-12-18 09:24
Closing this as it seems to be gone after doing a quick test run with `ember l10n:extract` due to the update from xgettext-parser from `2.6.0` to `3.4.0` in latest version.

```hbs
// app/templates/application.hbs
{{t '<No Name'}}
```

```po
#: app/templates/application.l10n.hbs:1
msgid "<No Name"
msgstr ""
```

**Closed by arm1n** 2017-12-18 09:24 UTC
Labels: bug
