### ISSUE TITLE
Hash values passed to t helper should not return the translated string 

### ISSUE THREAD

**Issue by ronaldcurtis** [Cropster/ember-l10n#17] opened 2017-08-25 00:27 UTC
Hi guys!

Just noticed something in my company's app when using your lib. It looks like param values passed to the t helper are also being translated. So for example:

`{{t "{{creator}} and {{count}} other" creator=displayName count=otherCreatorsCount}}`

Now, if there's a translation entry for the `creator` param, the translated value gets rendered!

I discovered that this is due to the `_strfmt` function [here](https://github.com/Cropster/ember-l10n/blob/master/addon/services/l10n.js#L435). Is there a reason we can't just return the param string as-is (`return value;` instead of `return gettext(value)`?

Just wondering if this is normal behaviour, and as to why it was implemented this way? 

Thanks 😄

**Comment by mydea** [comment] 2017-08-25 06:59
I think this is a duplicate of https://github.com/Cropster/ember-l10n/issues/15, and should be fixed in 0.3.0.

**Closed by mydea** 2017-08-25 06:59 UTC
